apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soju.fullname" . }}-config
  labels:
    {{- include "soju.labels" . | nindent 4 }}
data:
  config: |
    hostname {{ .Values.soju.domain }}
    title "{{ .Values.soju.title }}"
    db {{ include "soju.databaseDSN" . }}
    message-store db
    {{- if .Values.listeners.ircs }}
    listen ircs://0.0.0.0:6697
    {{- end }}
    {{- if .Values.listeners.irc }}
    listen irc+insecure://0.0.0.0:6667
    {{- end }}
    {{- if .Values.listeners.websocket }}
    listen ws+insecure://0.0.0.0:8080
    {{- end }}
    {{- if .Values.listeners.admin }}
    listen unix+admin:///run/soju/admin
    {{- end }}
    {{- if .Values.listeners.metrics }}
    listen http+prometheus://0.0.0.0:9090
    {{- end }}
    {{- if eq (include "soju.tlsEnabled" .) "true" }}
    tls /tls/tls.crt /tls/tls.key
    {{- end }}
    auth {{ .Values.auth.method }}
    {{- if .Values.fileUpload.enabled }}
    file-upload fs {{ .Values.fileUpload.path }}
    {{- end }}
    {{- if .Values.soju.motd }}
    motd {{ .Values.soju.motd }}
    {{- end }}
