{{- if and .Values.admin.enabled (not .Values.admin.existingSecret) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-admin" (include "soju.fullname" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soju.fullname" . }}-admin
  labels:
    {{- include "soju.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $existing }}
  admin-username: {{ index $existing.data "admin-username" }}
  admin-password: {{ index $existing.data "admin-password" }}
  {{- else }}
  admin-username: {{ (.Values.admin.username | default "admin") | b64enc | quote }}
  admin-password: {{ (.Values.admin.password | default (randAlphaNum 24)) | b64enc | quote }}
  {{- end }}
{{- end }}
