apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gamja.fullname" . }}-config
  labels:
    {{- include "gamja.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "server": {
        {{- if .Values.server.url }}
        "url": "{{ .Values.server.url }}"
        {{- else }}
        "url": "/socket"
        {{- end }}
        {{- if .Values.server.autojoin }},
        "autojoin": "{{ .Values.server.autojoin }}"
        {{- end }}
      }
    }
